### ISSUE TITLE
Function of Conv layer on Deep Biaffine parser

### ISSUE THREAD

**Issue by XuhuiZhou** [XuezheMax/NeuroNLP2#18]
Thank you for your nice and neat code for the re-implementation of the Stanford Deep BiAffine Parser. 
I notice that you used and Conv layer on in class BiRecurrentConvBiAffine at the beginning. 
Since in the original paper, they do not use the Conv layer, I am wondering what is the function of the Conv layer here? Is it just for features extraction? Or it actually plays an important role in your code?

**Comment by XuezheMax** [comment]
Conv layers are used for extracting character-level features. The details are described in our paper at ACL-2016:
https://arxiv.org/abs/1603.01354

**Comment by XuhuiZhou** [comment]
Thank you very much for the clarification 👍 
I looked into the paper above, and it seems that Conv layer plays a more important role here than I expect.

At first, I thought the **GraphParser.py** in the examples folder was exactly the re-implementation of **_DEEP BIAFFINE ATTENTION FOR NEURAL DEPENDENCY PARSING_** and it seems not the case now.

So I just want to confirm whether **GraphParser.py** is the re-implementation of the Stanford Deep BiAffine Parser?

If so, Is it OK for me to just delete the CNN layer? Or how much code will be changed if I have to disable the Conv layer?

**Comment by XuezheMax** [comment]
The only difference is the Conv layer, which you can disable by removing the --char argument in the running script.

**Comment by XuhuiZhou** [comment]
Yeah~It works, thank you very much!
One little suggestion, the logger info still shows the situation of CNN layer even if you disable the --char, which is kind of misleading.
Apart from that, everything works perfectly!
Thank you again for your nice code :)

**Comment by XuezheMax** [comment]
Thanks so much for your comments!
