### ISSUE TITLE
Predicted POS Tags

### ISSUE THREAD

**Issue by ghost** [XuezheMax/NeuroNLP2#20]
I assume the Biaf: re-impl scores are described with predicted tags.  For the predicted tags in the paper, where did the predicted tags come from?  Did they come from the tagger built by run_posCRFTagger.sh?  I did not notice a tool to predict a new CoNLL file as a result of a trained POS tagger model.

**Comment by XuezheMax** [comment]
The predicted tags were from the Stanford POS tagger. The parser assumes that the (predicted) pos tags are already provided in the training data file.
