### ISSUE TITLE
how to use Elmo or Bert

### ISSUE THREAD

**Issue by cjf9028** [XuezheMax/NeuroNLP2#37]
how to use Elmo or Bert
now i has pretrained Blmo and Bert

and i runnning Biaffine and stackpointer model 

i need your help

**Comment by XuezheMax** [comment]
For now, Elmo and Bert are not supported in this repo.
If you want to use them, you have to modify the code to include pre-trained representations, such as use these representations as input to the sequence labeling or parsing models.
