### ISSUE TITLE
embedding size

### ISSUE THREAD

**Issue by peithous** [XuezheMax/NeuroNLP2#38]
What is the size of glove embeddings that is required? I try glove trained with 100dims but I get an error
<img width="1424" alt="Screen Shot 2019-12-02 at 10 10 02 PM" src="https://user-images.githubusercontent.com/27439526/70017229-959eca00-1550-11ea-980a-48f50abbcf5f.png">

**Comment by XuezheMax** [comment]
It seems that your embedding is not loaded correctly.
Would you please print the word_dim to see if it is 100?
Or have you changed the config file where the hyps['word_dim'] should be
100 by default?

**Comment by peithous** [comment]
I load it in like this 
<img width="1424" alt="Screen Shot 2019-12-02 at 10 10 02 PM" src="https://user-images.githubusercontent.com/27439526/70018467-35118c00-1554-11ea-975c-6498f6d3dce4.png"> but I will try setting  hyps['word_dim'] as 100 right now and see if it works. I can't tell from parsing.py how word_dim is set... even though i see it on line 148

**Comment by peithous** [comment]
i get the same error when i set word_dim = 100 in the assert statement on 225, i would not mind hard coding the embedding dim, i just don't see how

**Comment by peithous** [comment]
with respect to the biaffine.json I did not change anything -- I thought training would work since I was loading in 100-dim glove embeddings (I also tried loading them in with the sskip option just in case and I got the same error).

**Comment by peithous** [comment]
I think that I am loading the embeddings correctly now, but I am getting a different error 
<img width="1250" alt="Screen Shot 2019-12-03 at 11 39 32 AM" src="https://user-images.githubusercontent.com/27439526/70070427-9cb1f080-15c1-11ea-8a00-65deb5a9a236.png">

**Comment by peithous** [comment]
The Greek conll file is a bit different than the English one, even after the same conversion from conllu
