### ISSUE TITLE
parsing input format

### ISSUE THREAD

**Issue by peithous** [XuezheMax/NeuroNLP2#39]

**Comment by XuezheMax** [comment]
Please try to delete the model path folder to restart again.
When you train a new model, the code will first look at the model path to load the alphabets back from disk if it exists. Thus, if you want to train a new model from scratch, please use a empty model path.

**Comment by peithous** [comment]
thanks! i eventually figured that out, changed the path and everything seems to be working.

**Comment by XuezheMax** [comment]
Great!
