### ISSUE TITLE
Interpretation of code variables

### ISSUE THREAD

**Issue by wjinfeng** [XuezheMax/NeuroNLP2#42]
Thank you for your open source work. 
Could you please explain the parsing method : **left2right, deep first, shallow first, inside out** in code of <Stack-Pointer Networks for Dependency Parsing>, 
looking forward to your reply

**Comment by XuezheMax** [comment]
These are the options for selecting the order of the children of a head word in the stack-pointer parser.
The stack-pointer parser, at each step, selects a child for the current head word. But it raises a question for head words that have multiple children: what is the order of these children?

For left2right, these children are ordered from left-to-right, i.e. selecting the left-most word first.
For inside-out, the child that closest to the head word is selected first.

In practice, inside-out works best. So we set inside-out as our default option.

**Comment by wjinfeng** [comment]
Thank you very much for your reply, it helped me a lot.
